package mx.itesm.CapturaDeFormularios;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class OpenFormula extends javax.swing.JFrame {
    
    static OpenFormula instance;
    
    public static OpenFormula Instance() {
        if (instance == null)
           instance = new OpenFormula();
        
        return instance;
    }
    
    static int lastAvailableId_Formularios = 0;
    
    public static int LastAvailableId_Formularios() {
        return lastAvailableId_Formularios;
    }
    
    public static void DecrementLastAvailableId_Formularios() {
        lastAvailableId_Formularios--;
    }
    
    static int lastAvailableId_Preguntas = 0;
    
    public static int LastAvailableId_Preguntas() {
        return lastAvailableId_Preguntas;
    }
    
    public static void DecrementLastAvailableId_Preguntas() {
        lastAvailableId_Preguntas--;
    }
    
    public static void IncrementLastAvailableId_Preguntas() {
        lastAvailableId_Preguntas++;
    }
    
    /**
     * Creates new form CapturaDeFormularios
     */
    public OpenFormula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(702, 499));

        jLabel1.setText("Bienvenido a OpenFormula, el software de creación y  captura de formularios de encuesta.");

        jButton1.setText("Ver formularios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Crear nuevo formulario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("OpenFormula");

        jButton4.setText("Vacíar tablas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel1)))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    lastAvailableId_Formularios++;
        
    try {
        Connection con = Conexion.getconexion();
        
        String query = "INSERT INTO Formularios (idFormulario) VALUES(" + lastAvailableId_Formularios + ");";
        
        PreparedStatement psmt = con.prepareStatement(query);
            
        psmt.execute();
        con.close();
    } catch (SQLException ex) {
        System.out.println(ex.getMessage());
    }   
        
        CrearFormulario crearFormulario = new CrearFormulario();
        crearFormulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ResponderFormulario responderFormulario = new ResponderFormulario();
        responderFormulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
                Connection con = Conexion.getconexion();

                String query = "DELETE FROM PreguntasAbiertas WHERE fkPregunta > 0;";
                PreparedStatement psmt = con.prepareStatement(query);
                psmt.execute();               
                
                query = "DELETE FROM PreguntasOpcionMultiple WHERE fkPregunta > 0;";
                psmt = con.prepareStatement(query);
                psmt.execute();                
               
                query = "DELETE FROM PreguntasSeleccionMultiple WHERE fkPregunta > 0;";
                psmt = con.prepareStatement(query);
                psmt.execute();                
                
                query = "DELETE FROM PreguntasSiNo WHERE fkPregunta > 0;";
                psmt = con.prepareStatement(query);
                psmt.execute();                

                query = "DELETE FROM RespuestasAbiertas WHERE fkRespuesta > 0;";
                psmt = con.prepareStatement(query);
                psmt.execute();

                query = "DELETE FROM RespuestasOpcionMultiple WHERE fkRespuesta > 0;";
                psmt = con.prepareStatement(query);
                psmt.execute();
                
                query = "DELETE FROM RespuestasSeleccionMultiple WHERE fkRespuesta > 0;";
                psmt = con.prepareStatement(query);
                psmt.execute();
                
                query = "DELETE FROM RespuestasSiNo WHERE fkRespuesta > 0;";
                psmt = con.prepareStatement(query);
                psmt.execute();                
                
                query = "DELETE FROM Respuestas WHERE idRespuesta > 0;";
                psmt = con.prepareStatement(query);
                psmt.execute();                
                
                query = "DELETE FROM Preguntas WHERE idPregunta > 0;";
                psmt = con.prepareStatement(query);
                psmt.execute();
                
                query = "DELETE FROM Usuarios WHERE idUsuario > 0;";
                psmt = con.prepareStatement(query);
                psmt.execute();     
                
                query = "DELETE FROM Formularios WHERE idFormulario > 0;";
                psmt = con.prepareStatement(query);
                psmt.execute();
                
                con.close();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpenFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpenFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpenFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenFormula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
